#!/usr/bin/env node
/* ============================================================================
 *  BUILD TOPICS INDEX
 * ----------------------------------------------------------------------------
 *  Course topics live in the lazy-loaded detail files (js/data/details/<field>/
 *  <id>.js), which the site only fetches when a card opens. To make topics
 *  searchable up front WITHOUT loading every detail file at runtime, this script
 *  extracts each course's topic list into a compact index:
 *
 *      js/data/topics-index.js  ->  window.KM_TOPICS = { "<id>": [topics], ... }
 *
 *  index.html loads that one small file eagerly; full card content stays lazy.
 *  Re-run after editing detail files:  node scripts/build-topics.js
 * ==========================================================================*/
"use strict";
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const detailsRoot = path.join(__dirname, "..", "js", "data", "details");
const outFile = path.join(__dirname, "..", "js", "data", "topics-index.js");

const index = {};
let files = 0, withTopics = 0, skipped = 0;

function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) { walk(p); continue; }
    if (!entry.name.endsWith(".js") || entry.name === "_detail.js") continue;
    files++;
    const id = entry.name.replace(/\.js$/, "");
    let captured = null;
    const sandbox = {
      registerDetail: (a, b) => { captured = typeof a === "string" ? b : a; },
      res: () => ({}),
      window: {}, document: undefined, console: { warn() {}, log() {} },
    };
    try {
      vm.runInContext(fs.readFileSync(p, "utf8"), vm.createContext(sandbox), { filename: p });
    } catch (err) {
      skipped++; console.warn(`  ! skipped ${path.relative(detailsRoot, p)} — ${err.message}`);
      continue;
    }
    if (captured && Array.isArray(captured.topics) && captured.topics.length) {
      index[id] = captured.topics.map(String);
      withTopics++;
    }
  }
}

walk(detailsRoot);

// Sort keys for a stable, diff-friendly file.
const sorted = {};
for (const k of Object.keys(index).sort()) sorted[k] = index[k];

const header =
  "/* AUTO-GENERATED by scripts/build-topics.js — do not edit by hand.\n" +
  "   Maps course id -> its topic list, so search can match topics without\n" +
  "   loading every detail file. Re-run: node scripts/build-topics.js */\n";
fs.writeFileSync(outFile, header + "window.KM_TOPICS = " + JSON.stringify(sorted) + ";\n");

console.log(`Scanned ${files} detail files → ${withTopics} with topics` +
  (skipped ? `, ${skipped} skipped` : "") + `.\nWrote ${path.relative(path.join(__dirname, ".."), outFile)}`);
